export { marka } from './marka'
export { avtotovar } from './avtotovar'
export { kuzov } from './kuzov'
export { maslo } from './maslo'
export { motor } from './motor'
export { shina } from './shina'
export { xodovoy } from './xodovoy'
export { zapchast } from './zapchast'
export { akkumlator } from './akkumlator'
export { tabLinksUz, tabLinksRu } from './tabmenu'